"use client";
import { useState } from "react";
import { Building2, Check, Copy, Phone, UsersRound } from "lucide-react";
import { Button, Card, PageHeading, SearchInput, Select } from "@/components/ui/Primitives";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui/States";
import { useToast } from "@/components/ui/Toast";
import { useResource } from "@/hooks/useResource";
import { phoneDirectoryService } from "@/services/phoneDirectoryService";
import { faNumber, matchesSearch } from "@/lib/utils";
import type { Department } from "@/types";

export function PhoneDirectory({ initial }: { initial: Department[] }) {
  const resource = useResource(phoneDirectoryService, initial); const toast = useToast(); const [query, setQuery] = useState(""); const [departmentId, setDepartmentId] = useState(""); const [copied, setCopied] = useState("");
  const active = resource.data.map((department) => ({ ...department, extensions: department.extensions.filter((entry) => entry.active) }));
  const filtered = active.filter((department) => !departmentId || department.id === departmentId).map((department) => ({ ...department, extensions: department.extensions.filter((entry) => matchesSearch(query, entry.name, entry.extension, department.name)) })).filter((department) => department.extensions.length);
  const total = active.reduce((sum, department) => sum + department.extensions.length, 0); const count = filtered.reduce((sum, department) => sum + department.extensions.length, 0);
  async function copy(extension: string) { try { await navigator.clipboard.writeText(extension); setCopied(extension); toast(`داخلی ${faNumber(extension)} کپی شد.`); } catch { toast("کپی خودکار در دسترس نیست. شماره داخلی را انتخاب و کپی کنید.", "error"); } }
  return <><PageHeading title="لیست واحدها و داخلی‌ها" description="همکار مورد نظرتان را به‌سادگی پیدا کنید." eyebrow="میز کار / شماره‌های داخلی" /><div className="directory-banner"><span className="directory-banner-icon"><Phone size={30} strokeWidth={1.4} /></span><div><h2>یک تماس، نزدیک‌تر به هم</h2><p>راه ارتباطی مستقیم با همکاران و واحدهای آذرشین</p></div><div className="directory-count"><strong>{faNumber(total)}</strong><span>شماره داخلی</span></div></div><Card className="directory-search-card"><div className="directory-search"><SearchInput value={query} onChange={setQuery} placeholder="نام همکار، واحد یا شماره داخلی..." /><Select aria-label="انتخاب واحد" value={departmentId} onChange={(event) => setDepartmentId(event.target.value)}><option value="">همه واحدها</option>{resource.data.map((department) => <option value={department.id} key={department.id}>{department.name}</option>)}</Select></div><div className="directory-summary"><span><Building2 size={14} />{faNumber(filtered.length)} واحد</span><span><UsersRound size={14} />{faNumber(count)} داخلی</span><span className="muted">برای کپی شماره، از دکمه کنار آن استفاده کنید.</span></div></Card>{resource.error ? <ErrorState message={resource.error} retry={resource.reload} /> : resource.loading ? <LoadingState /> : filtered.length ? <div className="directory-grid">{filtered.map((department) => <Card className="department-card" key={department.id}><div className="department-heading"><span><Building2 size={16} /><h2>{department.name}</h2></span><small>{faNumber(department.extensions.length)} داخلی</small></div><ul>{department.extensions.map((entry) => <li key={entry.id}><span className="extension-person"><span className="person-dot" />{entry.name}</span><div className="extension-actions"><a className="extension-number" href={`tel:${entry.extension}`} dir="ltr" aria-label={`تماس با ${entry.name}، داخلی ${entry.extension}`}>{entry.extension}</a><button className="icon-button copy-button" aria-label={`کپی داخلی ${entry.extension}`} onClick={() => void copy(entry.extension)}>{copied === entry.extension ? <Check size={14} /> : <Copy size={14} />}</button></div></li>)}</ul></Card>)}</div> : <Card><EmptyState title="داخلی مورد نظر پیدا نشد." description="نام، شماره یا واحد دیگری را جستجو کنید." action={<Button variant="secondary" onClick={() => { setQuery(""); setDepartmentId(""); }}>نمایش همه داخلی‌ها</Button>} /></Card>}</>;
}
